import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

/**
 * UserProfile Component
 * Generated by CodeMate Pro
 */
@Component({
  selector: 'app-user-profile',
  template: `
    <div class="user-profile-container" [ngClass]="customClass">
      <div class="user-profile-content">
        <ng-container *ngIf="!isLoading; else loadingTemplate">
          <ng-content></ng-content>
        </ng-container>
        <ng-template #loadingTemplate>
          <span>Loading...</span>
        </ng-template>
      </div>
    </div>
  `,
  styles: [`
    .user-profile-container {
      display: block;
    }
    .user-profile-content {
      padding: 1rem;
    }
  `]
})
export class UserProfileComponent implements OnInit, OnDestroy {
  @Input() customClass = '';
  @Input() isLoading = false;
  @Output() actionTriggered = new EventEmitter<void>();

  ngOnInit(): void {
    // Component initialization logic
  }

  ngOnDestroy(): void {
    // Cleanup logic
  }

  onAction(): void {
    this.actionTriggered.emit();
  }
}
